name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch files from Github Repository
        uses: actions/checkout@v4

      - name : Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependency
        run: npm ci

      - name: .env 파일 만들기
        run: |
          echo '${{ secrets.ENV }}' > .env

      - name: Set up AWS credentials to access AWS Resource
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create Docker image
        run: docker build -t gymlog-server .

      - name: Add tag to Docker image
        run: docker tag gymlog-server ${{ steps.login-ecr.outputs.registry }}/gymlog-server:latest

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/gymlog-server:latest

      - name: Connect EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script_stop: true
            script: |
              docker stop gymlog-server || true
              docker rm gymlog-server || true
              docker pull ${{ steps.login-ecr.outputs.registry }}/gymlog-server:latest
              docker run -d --name gymlog-server -p 80:80 ${{ steps.login-ecr.outputs.registry }}/gymlog-server:latest
