name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name : Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성(라이브러리)설치
        run: npm ci

      - name: .env 파일 만들기
        run: |
          echo '${{ secrets.ENV }}' > .env.prod

      - name: 빌드
        run: npm run build

      - name: 압축하기
        run: tar -czvf project.tar.gz dist .env.prod package.json package-lock.json

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.tar.gz
          target: /home/ubuntu/nestjs-gymlog/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{secrets.ENV}}
        with:
          host: ${{secrets.EC2_HOST}} # EC2 의 주소
          username: ${{secrets.EC2_USERNAME}}  # EC2 접속 유저네임
          key: ${{secrets.EC2_PRIVATE_KEY}} # EC2의 key 파일의 내부 텍스트
          envs: ENV
          script_stop: true # 아래 script 중 실패하는 명령어 하나라도 있으면 실패로 처리
          script: |
            rm -rf /home/ubuntu/nestjs-gymlog/current
            mkdir /home/ubuntu/nestjs-gymlog/current
            mv /home/ubuntu/nestjs-gymlog/tobe/project.tar.gz /home/ubuntu/nestjs-gymlog/current/project.tar.gz
            cd /home/ubuntu/nestjs-gymlog/current
            tar -xvf project.tar.gz
            npm i
            sudo pm2 kill
            pm2 kill
            sudo npm run start:prod